<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Surajs-MacBook-Pro.local" ignored="0" name="Free CRM App Test" tests="9" failures="2" timestamp="2020-04-27T22:49:53 NPT" time="0.048" errors="0">
  <testcase name="Test1" time="0.007" classname="com.crm.qa.testcases.ReTryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="com.crm.qa.testcases.ReTryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="com.crm.qa.testcases.ReTryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="com.crm.qa.testcases.ReTryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.crm.qa.testcases.ReTryTest.Test1(ReTryTest.java:11)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.001" classname="com.crm.qa.testcases.ReTryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="com.crm.qa.testcases.ReTryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="com.crm.qa.testcases.ReTryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="com.crm.qa.testcases.ReTryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.crm.qa.testcases.ReTryTest.Test2(ReTryTest.java:16)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.001" classname="com.crm.qa.testcases.ReTryTest"/>
</testsuite> <!-- Free CRM App Test -->
